; File autogenerated by build-flavored-queries.py; do not edit

; This file specifies how matched syntax patterns should be highlighted

[
  "export"
  "import"
] @keyword.control.import.just

"mod" @entity.name.namespace.just

[
  "alias"
  "set"
  "shell"
] @keyword.control.just

[
  "if"
  "else"
] @keyword.control.conditional.just

; Variables

(value
  (identifier) @variable.other.just)

(alias
  left: (identifier) @variable.other.just)

(assignment
  left: (identifier) @variable.other.just)

; Functions

(recipe_header
  name: (identifier) @entity.name.function.just)

(dependency
  name: (identifier) @support.other.function.just)

(dependency_expression
  name: (identifier) @support.other.function.just)

(function_call
  name: (identifier) @support.other.function.just)

; Parameters

(parameter
  name: (identifier) @variable.parameter.just)

; Namespaces

(module
  name: (identifier) @entity.name.namespace.just)

; Operators

[
  ":="
  "?"
  "=="
  "!="
  "=~"
  "@"
  "="
  "$"
  "*"
  "+"
  "&&"
  "@-"
  "-@"
  "-"
  "/"
  ":"
] @keyword.operator.just

; Punctuation

"," @punctuation.separator.comma.just

"{" @punctuation.definition.block.begin.bracket.curly.just
"}" @punctuation.definition.block.end.bracket.curly.just
"[" @punctuation.definition.attribute.begin.bracket.square.just
"]" @punctuation.definition.attribute.end.bracket.square.just
"(" @punctuation.definition.arguments.begin.bracket.round.just
")" @punctuation.definition.arguments.end.bracket.round.just

; `{{ … }}` interpolates an expression into a recipe line.
"{{" @punctuation.definition.template-expression.begin.just
"}}" @punctuation.definition.template-expression.end.just

; Backticks run a shell command and substitute its output.
[ "`" "```" ] @punctuation.definition.backtick.just

; Literals

(boolean) @constant.language.boolean.just

[
  (string)
  (external_command)
] @string.quoted.double.just

(escape_sequence) @constant.character.escape.just

; Comments

(comment) @_IGNORE_.spell @comment.line.just

(shebang) @keyword.control.directive.just

; highlight known settings (filtering does not always work)
(setting
  left: (identifier) @keyword.control.just
  (#any-of? @keyword.control.just
    "allow-duplicate-recipes"
    "allow-duplicate-variables"
    "dotenv-filename"
    "dotenv-load"
    "dotenv-path"
    "dotenv-required"
    "export"
    "fallback"
    "ignore-comments"
    "positional-arguments"
    "shell"
    "shell-interpreter"
    "tempdir"
    "windows-powershell"
    "windows-shell"
    "working-directory"))

; highlight known attributes (filtering does not always work)
(attribute
  (identifier) @entity.other.attribute-name.just
  (#any-of? @entity.other.attribute-name.just
    "confirm"
    "doc"
    "extension"
    "group"
    "linux"
    "macos"
    "metadata"
    "no-cd"
    "no-exit-message"
    "no-quiet"
    "openbsd"
    "parallel"
    "positional-arguments"
    "private"
    "script"
    "unix"
    "windows"
    "working-directory"))

; Numbers are part of the syntax tree, even if disallowed
(numeric_error) @invalid.illegal.just
